### PR TITLE
update template to expo v16

### PR DESCRIPTION
**Pull request by gonewest818**
Adjusted as per the documented steps on the expo.io blog:

https://blog.expo.io/expo-sdk-v16-0-0-is-now-available-2151d555a580

But with full disclosure, I am new to exponent, so a more experienced review and/or test is warranted. At the very least, the default code in this template does build and run properly.

### CODE REVIEW

**Comment by ducky427** [comment]
Has this been tested locally?

I'd be careful of using react `16.0.0-alpha.6` with reagent as its not been tested and it does have a breaking change [removal of `React.createClass`].

**Comment by gonewest818** [comment]
That's a nuance I simply didn't know. Fully admit I have little experience in this, and when I asked on the slack channel if it was valid to simply bump the versions the first answer was, "I think so, would accept a PR."  So I can close this PR or leave it in the queue or ...

**Comment by tiensonqin** [comment]
@gonewest818 @ducky427 Sorry for the late response, 
If anyone can confirm react 16.0.0-alpha.6 works well with reagent, I'll definitely merge this PR.

**Comment by gonewest818** [comment]
Sorry, I haven’t tested. Based on what @ducky427 said, I’d say the reagent community needs some time to adjust to at least one breaking change.

**Comment by seantempesta** [comment]
So, this is anecdotal, but I went ahead and updated to react 16.0.0-alpha.6 and my project is working fine.  What problems specifically are there supposed to be with the new React?  From my understanding the API stayed the same and the underlying implementation changed.

**Comment by gonewest818** [comment]
I don't know any specific problems. The react 16 changes are tracked in an umbrella here and the change ducky427 mentioned is actually something that was deprecated in 15. So provided the reagent project is on the ball with the deprecated code, you might be right. 

https://github.com/facebook/react/issues/8854

**Comment by seantempesta** [comment]
Tested and it works on my machine!  Also, I've been using reagent "0.6.1", react "16.0.0.alpha.6" and exponent for a while without any problems.  So we should probably move to the newer version of reagent.  But for now, let's merge this.

**Pull request merged**
